apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: local-storage
  reclaimPolicy: Retain # retain storage or delete (default) after PVC is released
  provisioner: kubernetes.io/no-provisioner # provisioner (volume plugin) that will be used to create PersistentVolume resource
  volumeBindingMOde: WaitForFirstConsumer # wait to create until Pod making PVC is created. Default is immediate (create once PVC is created)
  